sources:
  - service
  - ingress

policy: sync
triggerLoopOnEvent: true
registry: txt
txtOwnerId: "cluster-name"
#txtPrefix: ""
#txtSuffix: ""

env:
- name: HETZNER_TOKEN
  value: "token_here"
  
domainFilters: ["technat.dev",".technat.dev"]
provider: hetzner
resources:
  limits:
    cpu: 200m
    memory: 100Mi
  requests:
    cpu: 10m
    memory: 50Mi
