baseURL = 'https://technat.ch'
title = "Nathanael Liechti"
theme = 'm10c'

[params]
  author = "Nathanael Liechti"
  description = "Kubernetes Platform Engineer, minimalist, perfectionist and optimist with no memories of classic IT"
  avatar = "images/avatar.jpeg"
  menu_item_separator = " - "
   [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/the-technat"
     # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"
  #  primaryColor = "#dad865"
