baseURL = 'https://technat.ch/'
title = "technat.ch"
author = "Nathanael Liechti"
languageCode = 'en'
DefaultContentLanguage = "en"
enableInLineShortcodes = true
theme = 'holy'

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "github"
    name = "Github"
    url = "https://github.com/the-technat"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
