#cloud-config <hostname>
# cloud-init devel schema --config-file myconfig.yaml to verify

package_update: true
package_upgrade: true
packages:
  - dnsutils
  - net-tools
  - curl
  - wget
  - git
  - ufw
  - postgresql
  - postgresql-client
  - postgresql-contrib

users:
  - name: technat
    groups: sudo
    sudo: ALL=(ALL) NOPASSWD:ALL # Allow any operations using sudo
    gecos: "Admin user created by cloud-init"
    ssh_authorized_keys:
      - ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFI7+bAmoBNcITqKlmCZIPuN1LY7gL3ejUfL5LDl9nNZEx9SQmNVpRqDEJUbERGQ43B/VdARwyw8fW75j633dFI= switch_engines_insy@secretive.WALL-E.local

write_files:
  - path: /etc/sysctl.d/99-tailscale.conf
    content: |
      net.ipv4.ip_forward          = 1
      net.ipv6.conf.all.forwarding = 1
  - path: /etc/apt/apt.conf.d/50unattended-upgrades
    content: |
      Unattended-Upgrade::Allowed-Origins {
        "${distro_id}:${distro_codename}";
        "${distro_id}:${distro_codename}-security";
        "${distro_id}ESMApps:${distro_codename}-apps-security";
        "${distro_id}ESM:${distro_codename}-infra-security";
        "${distro_id}:${distro_codename}-updates";
        "${distro_id}:${distro_codename}-proposed";
        "${distro_id}:${distro_codename}-backports";
      };
      Unattended-Upgrade::DevRelease "auto";
      Unattended-Upgrade::Remove-Unused-Dependencies "true";
      Unattended-Upgrade::Automatic-Reboot "true";
      Unattended-Upgrade::Automatic-Reboot-Time "23:00";
      Unattended-Upgrade::SyslogEnable "true";
  - path: /usr/local/bin/setup_postgres.sh
    permissions: "0700"
    content: |
      #!/bin/sh
      DB_NAME="insy"
      ADMIN_PASSWORD=$(openssl rand -base64 15)
      PG_VERSION=$(psql --version | awk '{print $3}' | cut -d. -f1)
      echo "$ADMIN_PASSWORD" > /root/postgres_password.txt
      sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD '${ADMIN_PASSWORD}';"
      sed -i 's/^#listen_addresses.*/listen_addresses = '\''*'\''/' /etc/postgresql/$PG_VERSION/main/postgresql.conf 
      echo "host all all 0.0.0.0/0 md5" | sudo tee -a /etc/postgresql/$PG_VERSION/main/pg_hba.conf
      sudo -u postgres psql -c "CREATE DATABASE ${DB_NAME};"
      curl -fsSL -o /tmp/create_tables_all.sql https://kgdeck.github.io/db_exercises/data/create_tables_all.sql
      curl -fsSL -o /tmp/insert_all.sql https://kgdeck.github.io/db_exercises/data/insert_all.sql
      sudo -u postgres psql -d ${DB_NAME} -f /tmp/create_tables_all.sql
      sudo -u postgres psql -d ${DB_NAME} -f /tmp/insert_all.sql
      echo "You can use the DB system on this VM using the admin 'postgres' and the password found in /root/postgres_password.txt"
      echo "Connect to this host using IP $(ip -o -4 addr show scope global | awk '{print $4}' | cut -d/ -f1 | head -n1) and Port 5432"

runcmd:
  - sysctl -p /etc/sysctl.d/99-tailscale.conf
  - systemctl enable --now unattended-upgrades.service
  - curl -fsSL https://tailscale.com/install.sh | sh
  - /usr/local/bin/setup_postgres.sh
  - systemctl restart postgresql
  - ufw default deny incoming
  - ufw default allow outgoing
  - ufw allow 22/tcp
  - ufw allow 5432/tcp # open DB port to the outside world
  -  #systemctl mask ssh
  -  #tailscale up --ssh --auth-key "<single-use-pre-approved-key>"
