apiVersion: v1
kind: Service
metadata:
  name: heimdall-external
  namespace: heimdall
  labels:
    app.kubernetes.io/instance: heimdall
    app.kubernetes.io/name: heimdall
spec:
  ports:
  - name: dashboard
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/instance: heimdall
    app.kubernetes.io/name: heimdall
  type: LoadBalancer
